import { Navbar } from "@/components/Navbar";
import { Footer } from "./components/Footer";

export const metadata = {
  title: "Hair by Cassie",
  description: "Generated by shawnie",
};

const links = [
  {
    link: "/",
    label: "Home",
  },
  {
    link: "/about",
    label: "About",
  },
  {
    link: "/services",
    label: "Services",
  },
  {
    link: "/gallery",
    label: "Gallery",
  },
  {
    link: "/contact",
    label: "Contact",
  },
];

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>
        <Navbar links={links}></Navbar>
        {children}
        <Footer />
      </body>
    </html>
  );
}
