import "./globals.css";
import { Analytics } from "@vercel/analytics/react";
import Navbar from "@/components/Navbar";
import Footer from "@/components/footer";
import { INavLink } from "@/models/INavLink";

export const metadata = {
  title: "CVSS",
  description: "Generated by shawnie",
};

const navLinks: INavLink[] = [
  { name: "Home", url: "/" },
  { name: "About", url: "/about" },
  { name: "Contact", url: "/contact" },
  { name: "Book", url: "/book" },
];

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>
        <Navbar navLinks={navLinks} />
        {children}
        <Footer />
        <Analytics />
      </body>
    </html>
  );
}
